### ISSUE TITLE
Cheatsheet

### ISSUE THREAD

**Issue by Kaixhin** [hughperkins/dockerfiles#1]
Thanks for working on OpenCL versions! I have no experience in this area, and it would be good to have support. Remember to add it to the list of images on the [cheatsheet](https://github.com/torch/torch7/wiki/Cheatsheet#docker-images) when you're happy with them :)

You'll notice that in my latest commit (https://github.com/Kaixhin/dockerfiles/commit/5f5005562ebd654164951ddba4e672b6f3ab89fd) I realised that the environment variables didn't persist, so for now I'm adding them manually. If you spot issues with Torch7 on Docker then let me know, and I'll try to do the same.

**Comment by hughperkins** [comment]
k :-)  Theyre mostly for play really: I doubt many people will be using opencl to train on nvidia cards.  AMD cards as far as i know dont support docker?

**Comment by Kaixhin** [comment]
Yes, Docker is ideally hardware agnostic, but there were solutions for NVIDIA cards before the official project so perhaps there are some who've found solutions for AMD cards. Doubt it'll be easy or flexible though.
